/**
 * Mock Data for Development
 * Temporary data for collections and products
 */

import { Collection, Product } from './types';
import { getPlaceholderImage } from './placeholders';

export const mockCollections: Collection[] = [
  {
    id: '1',
    name: 'Silk Sarees',
    slug: 'silk',
    description: 'Luxurious silk weaves for special occasions',
    image: getPlaceholderImage(800, 600, 'Silk Sarees'),
    productCount: 48,
    featured: true,
  },
  {
    id: '2',
    name: 'Cotton Sarees',
    slug: 'cotton',
    description: 'Comfort and elegance for everyday wear',
    image: getPlaceholderImage(800, 600, 'Cotton Sarees'),
    productCount: 62,
    featured: true,
  },
  {
    id: '3',
    name: 'Handloom Sarees',
    slug: 'handloom',
    description: 'Authentic handwoven masterpieces',
    image: getPlaceholderImage(800, 600, 'Handloom Sarees'),
    productCount: 35,
    featured: true,
  },
  {
    id: '4',
    name: 'Festive Sarees',
    slug: 'festive',
    description: 'Celebrate in style with vibrant designs',
    image: getPlaceholderImage(800, 600, 'Festive Sarees'),
    productCount: 28,
    featured: true,
  },
];

export const mockFeaturedProducts: Product[] = [
  {
    id: '1',
    name: 'Kanchipuram Silk Saree',
    slug: 'kanchipuram-silk-saree',
    description: 'Traditional Kanchipuram silk saree with intricate zari work',
    shortDescription: 'Pure silk with gold zari border',
    price: 12500,
    regularPrice: 12500,
    onSale: false,
    images: [
      {
        id: '1',
        src: getPlaceholderImage(600, 800, 'Kanchipuram Silk'),
        alt: 'Kanchipuram Silk Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '1', name: 'Silk', slug: 'silk' },
    ],
    attributes: [
      { name: 'New Arrival', value: 'true' },
    ],
    sareeAttributes: {
      fabric: 'Silk',
      weave: 'Kanchipuram',
      occasion: ['Wedding', 'Festival'],
      care: 'Dry clean only',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Maroon', 'Gold'],
    },
    inStock: true,
    stockQuantity: 5,
    sku: 'KANCH-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Banarasi Silk Saree',
    slug: 'banarasi-silk-saree',
    description: 'Elegant Banarasi silk saree with traditional motifs',
    shortDescription: 'Pure Banarasi silk with floral patterns',
    price: 15000,
    regularPrice: 15000,
    onSale: false,
    images: [
      {
        id: '2',
        src: getPlaceholderImage(600, 800, 'Banarasi Silk'),
        alt: 'Banarasi Silk Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '1', name: 'Silk', slug: 'silk' },
    ],
    attributes: [
      { name: 'New Arrival', value: 'true' },
    ],
    sareeAttributes: {
      fabric: 'Silk',
      weave: 'Banarasi',
      occasion: ['Wedding', 'Festival', 'Party'],
      care: 'Dry clean only',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Deep Green', 'Gold'],
    },
    inStock: true,
    stockQuantity: 3,
    sku: 'BANAR-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Handloom Cotton Saree',
    slug: 'handloom-cotton-saree',
    description: 'Beautiful handloom cotton saree with traditional border',
    shortDescription: 'Handwoven cotton with contrast border',
    price: 4500,
    regularPrice: 4500,
    onSale: false,
    images: [
      {
        id: '3',
        src: getPlaceholderImage(600, 800, 'Handloom Cotton'),
        alt: 'Handloom Cotton Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '2', name: 'Cotton', slug: 'cotton' },
      { id: '3', name: 'Handloom', slug: 'handloom' },
    ],
    attributes: [
      { name: 'Handloom', value: 'true' },
    ],
    sareeAttributes: {
      fabric: 'Cotton',
      weave: 'Handloom',
      occasion: ['Casual', 'Festival'],
      care: 'Hand wash cold',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Blue', 'Gold'],
    },
    inStock: true,
    stockQuantity: 10,
    sku: 'HAND-COTTON-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Festive Silk Saree',
    slug: 'festive-silk-saree',
    description: 'Vibrant festive silk saree with rich colors',
    shortDescription: 'Perfect for celebrations',
    price: 8500,
    regularPrice: 8500,
    onSale: false,
    images: [
      {
        id: '4',
        src: getPlaceholderImage(600, 800, 'Festive Silk'),
        alt: 'Festive Silk Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '1', name: 'Silk', slug: 'silk' },
      { id: '4', name: 'Festive', slug: 'festive' },
    ],
    attributes: [
      { name: 'New Arrival', value: 'true' },
    ],
    sareeAttributes: {
      fabric: 'Silk',
      weave: 'Traditional',
      occasion: ['Festival', 'Party'],
      care: 'Dry clean only',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Pink', 'Gold'],
    },
    inStock: true,
    stockQuantity: 8,
    sku: 'FEST-SILK-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Mangalagiri Cotton Saree',
    slug: 'mangalagiri-cotton-saree',
    description: 'Classic Mangalagiri cotton saree with traditional weave',
    shortDescription: 'Lightweight and comfortable',
    price: 3500,
    regularPrice: 3500,
    onSale: false,
    images: [
      {
        id: '5',
        src: getPlaceholderImage(600, 800, 'Mangalagiri Cotton'),
        alt: 'Mangalagiri Cotton Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '2', name: 'Cotton', slug: 'cotton' },
    ],
    attributes: [],
    sareeAttributes: {
      fabric: 'Cotton',
      weave: 'Mangalagiri',
      occasion: ['Casual', 'Formal'],
      care: 'Machine wash cold',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Green'],
    },
    inStock: true,
    stockQuantity: 12,
    sku: 'MANG-COTTON-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Pochampally Silk Saree',
    slug: 'pochampally-silk-saree',
    description: 'Authentic Pochampally ikat silk saree',
    shortDescription: 'Traditional ikat patterns',
    price: 11000,
    regularPrice: 11000,
    onSale: false,
    images: [
      {
        id: '6',
        src: getPlaceholderImage(600, 800, 'Pochampally Silk'),
        alt: 'Pochampally Silk Saree',
        position: 1,
      },
    ],
    categories: [
      { id: '1', name: 'Silk', slug: 'silk' },
      { id: '3', name: 'Handloom', slug: 'handloom' },
    ],
    attributes: [
      { name: 'Handloom', value: 'true' },
    ],
    sareeAttributes: {
      fabric: 'Silk',
      weave: 'Pochampally',
      occasion: ['Wedding', 'Party'],
      care: 'Dry clean only',
      length: '6.3 meters',
      blouse: 'Included',
      color: ['Orange', 'Yellow'],
    },
    inStock: true,
    stockQuantity: 4,
    sku: 'POCH-SILK-001',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
